version: '3.8'

services:
  zo_test_etalik_app:
    depends_on:
      - db_etalik
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www/html
    container_name: zo_test_etalik_app
    ports:
      - "8080:80" 
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - .:/var/www/html
      - ./docker/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/xdebug.log:/var/www/xdebug.log
    restart: always

  db_etalik:
    image: 'mariadb:10.5'
    container_name: db_etalik
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'etalik_test'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db_etalik-db-data:/var/lib/mysql/
    ports:
      - '3313:3306'

volumes:
  db_etalik-db-data:
